services:
  bluelink_github_registry:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: bluelink_github_registry
    environment:
      BLUELINK_GITHUB_REGISTRY_BASE_URL: ${BLUELINK_GITHUB_REGISTRY_BASE_URL}
      BLUELINK_GITHUB_REGISTRY_SIGNING_PUBLIC_KEYS: ${BLUELINK_GITHUB_REGISTRY_SIGNING_PUBLIC_KEYS}
    networks:
      - gh_registry_network
    ports:
      - 8085:8085
    volumes:
      - ./:/app/bluelink_github_registry

  nginx:
    image: nginx:latest
    container_name: bluelink_github_registry_nginx
    networks:
      - gh_registry_network
    ports:
      - 80:80
    volumes:
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf

networks:
  gh_registry_network:
    name: gh_registry_network
